### ISSUE TITLE
Runtime error when trying to send message

### ISSUE THREAD

**Issue by iansu** [rkbalgi/isosim#5]
I'm attempting to send a message using this simulator and it's producing a runtime error in go. The message I'm trying to send is identical to the one in the screenshot in the README. This is the error I'm getting:

```
2019/06/20 13:34:04 http: panic serving [::1]:62956: runtime error: invalid memory address or nil pointer dereference
goroutine 114 [running]:
net/http.(*conn).serve.func1(0xc0000b81e0)
	/usr/local/opt/go/libexec/src/net/http/server.go:1769 +0x139
panic(0x131a840, 0x1610c80)
	/usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
github.com/rkbalgi/isosim/web/http_handlers.ToJsonList(0x0, 0x0, 0x0, 0x4852)
	/Users/iansu/.go/src/github.com/rkbalgi/isosim/web/http_handlers/parse_trace_handler.go:101 +0x66
github.com/rkbalgi/isosim/web/http_handlers.sendMsgHandler.func1(0x13edb60, 0xc000360000, 0xc000178100)
	/Users/iansu/.go/src/github.com/rkbalgi/isosim/web/http_handlers/send_msg_handler.go:110 +0xbad
net/http.HandlerFunc.ServeHTTP(0x138f570, 0x13edb60, 0xc000360000, 0xc000178100)
	/usr/local/opt/go/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x161cfa0, 0x13edb60, 0xc000360000, 0xc000178100)
	/usr/local/opt/go/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000132340, 0x13edb60, 0xc000360000, 0xc000178100)
	/usr/local/opt/go/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0000b81e0, 0x13ee460, 0xc0003540c0)
	/usr/local/opt/go/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/opt/go/libexec/src/net/http/server.go:2884 +0x2f4
```

Any help would be appreciated. Thanks.

**Comment by rkbalgi** [comment]
Hi Ian, 
I wasn't able to reproduce the issue locally (although I'm using windows and you're probably on linux or a mac)

In the data directory you provided, there will be a numeric folder with a JSON file underneath. Can you get me the JSON file contents? Also, I'm not sure if you've changed the spec definition (isoSpecs.spec). if so, I will need to see that too.

Thanks.

**Comment by rkbalgi** [comment]
Please reopen if you see that the issue still persists. Thanks.
